services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 123ferry_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
